### PR TITLE
Kickstart tooling subcommittee

### PR DESCRIPTION
**Pull request by alexandruradovici**
This pull request adds the documents to kickstart the tooling subcommittee. Please feel free to suggest any changes that you think are necessary.

Thanks @PLeVasseur for setting up a good template for the subcommittee.

Thank you.

### CODE REVIEW

**Review by PLeVasseur — APPROVED** [review]
Couple of nits, but otherwise LGTM!

**Review by JoelMarcey — APPROVED** [review]
Thanks!

**Comment by JoelMarcey** [comment]
Will merge after @alexandruradovici fixes nits from @PLeVasseur.

**Comment by alexandruradovici** [comment]
> Will merge after @alexandruradovici fixes nits from @PLeVasseur.

Maybe keep the PR a few more days around, I will announce it on Zulip and maybe other can contribute to it.

**Comment by JoelMarcey** [comment]
@alexandruradovici Can this be merged now?

**Pull request merged**
